/***************************
** INSERTIONS DES DONNEES **
****************************/
--PEREIRA--LOUNIS, BOURDELET, BOISSERIE, MARTIN--

--Insertion des données dans la table PARTIE--
INSERT INTO PARTIE VALUES(1, '20/12/2017');
INSERT INTO PARTIE VALUES(2, '06/05/2018');
INSERT INTO PARTIE VALUES(3, '19/07/2019');
INSERT INTO PARTIE VALUES(4, '03/05/2020');
INSERT INTO PARTIE VALUES(5, '03/12/2021');

--Insertion des données dans la table INDIVIDU--
INSERT INTO INDIVIDU VALUES(1, 'Morte', 'Alvaro', 48, 'Acteur');
INSERT INTO INDIVIDU VALUES(2, 'Corbero', 'Úrsula', 33, 'Acteur');
INSERT INTO INDIVIDU VALUES(3, 'Ituño', 'Itziar', 48, 'Acteur');
INSERT INTO INDIVIDU VALUES(4, 'Alonso', 'Pedro', 51, 'Acteur');
INSERT INTO INDIVIDU VALUES(5, 'Flores', 'Alba', 36, 'Acteur');
INSERT INTO INDIVIDU VALUES(6, 'Harràn', 'Miguel', 27, 'Acteur');
INSERT INTO INDIVIDU VALUES(7, 'Lorrente', 'Jaime', 31, 'Acteur');
INSERT INTO INDIVIDU VALUES(8, 'Tous', 'Paco', 59, 'Acteur');
INSERT INTO INDIVIDU VALUES(9, 'Peric', 'Darko', 46, 'Acteur');
INSERT INTO INDIVIDU VALUES(10, 'Acebo', 'Esther', 40, 'Acteur');
INSERT INTO INDIVIDU VALUES(11, 'Garcia', 'Roberto', 49, 'Acteur');
INSERT INTO INDIVIDU VALUES(12, 'Arce', 'Enrique', 50, 'Acteur');
INSERT INTO INDIVIDU VALUES(13, 'Soto', 'Fernando', 54, 'Acteur');
INSERT INTO INDIVIDU VALUES(14, 'Pedraza', 'Maria', 27, 'Acteur');
INSERT INTO INDIVIDU VALUES(15, 'Manver', 'Kiti', 70, 'Acteur');
INSERT INTO INDIVIDU VALUES(16, 'de la Selva', 'Rodrigo', 47, 'Acteur');
INSERT INTO INDIVIDU VALUES(17, 'Keuchkerian', 'Hovik', 50, 'Acteur');
INSERT INTO INDIVIDU VALUES(18, 'Perros', 'Luka', 46, 'Acteur');
INSERT INTO INDIVIDU VALUES(19, 'Cuesta', 'Belén', 39, 'Acteur');
INSERT INTO INDIVIDU VALUES(20, 'Cayo', 'Fernando', 55, 'Acteur');
INSERT INTO INDIVIDU VALUES(21, 'Nimri', 'Najwa', 51, 'Acteur');
INSERT INTO INDIVIDU VALUES(22, 'Colmenar', 'Jesús', NULL, 'Réalisateur');
INSERT INTO INDIVIDU VALUES(23, 'Serra', 'Koldo', 48, 'Réalisateur');
INSERT INTO INDIVIDU VALUES(24, 'Rodrigo', 'Álex', 60, 'Réalisateur');
INSERT INTO INDIVIDU VALUES(25, 'Quintas', 'Javier', 35, 'Réalisateur');

--Insertion des données dans la table EPISODE--
INSERT INTO EPISODE VALUES (1, 1, NULL, 'Episode 1', NULL, 1);
INSERT INTO EPISODE VALUES (2, 2, NULL, 'Episode 2', NULL, 1);
INSERT INTO EPISODE VALUES (3, 3, NULL, 'Episode 3', NULL, 1);
INSERT INTO EPISODE VALUES (4, 4, NULL, 'Episode 4', NULL, 1);
INSERT INTO EPISODE VALUES (5, 5, NULL, 'Episode 5', NULL, 1);
INSERT INTO EPISODE VALUES (6, 6, NULL, 'Episode 6', NULL, 1);
INSERT INTO EPISODE VALUES (7, 7, NULL, 'Episode 7', NULL, 1);
INSERT INTO EPISODE VALUES (8, 8, NULL, 'Episode 8', NULL, 1);
INSERT INTO EPISODE VALUES (9, 9, NULL, 'Episode 9', NULL, 1);
INSERT INTO EPISODE VALUES (10, 10, NULL, 'Episode 10', NULL, 1);
INSERT INTO EPISODE VALUES (11, 11, NULL, 'Episode 11', NULL, 1);
INSERT INTO EPISODE VALUES (12, 12, NULL, 'Episode 12', NULL, 1);
INSERT INTO EPISODE VALUES (13, 13, NULL, 'Episode 13', NULL, 1);
INSERT INTO EPISODE VALUES (14, 1, NULL, 'Episode 14', NULL, 2);
INSERT INTO EPISODE VALUES (15, 2, NULL, 'Episode 15', NULL, 2);
INSERT INTO EPISODE VALUES (16, 3, NULL, 'Episode 16', NULL, 2);
INSERT INTO EPISODE VALUES (17, 4, NULL, 'Episode 17', NULL, 2);
INSERT INTO EPISODE VALUES (18, 5, NULL, 'Episode 18', NULL, 2);
INSERT INTO EPISODE VALUES (19, 6, NULL, 'Episode 19', NULL, 2);
INSERT INTO EPISODE VALUES (20, 7, NULL, 'Episode 20', NULL, 2);
INSERT INTO EPISODE VALUES (21, 8, NULL, 'Episode 21', NULL, 2);
INSERT INTO EPISODE VALUES (22, 9, NULL, 'Episode 22', NULL, 2);
INSERT INTO EPISODE VALUES (23, 1, 'Hemos vuelto', 'On est de retour', 22, 3);
INSERT INTO EPISODE VALUES (24, 2, 'Aikido', 'Aïkido', 22, 3);
INSERT INTO EPISODE VALUES (25, 3, '48 metros bajo el suelo', '48 mètres sous terre', 22, 3);
INSERT INTO EPISODE VALUES (26, 4, 'La hora del delfín', 'L Heure du dauphin', 23, 3);
INSERT INTO EPISODE VALUES (27, 5, 'Bum, bum, ciao', 'Boum, boum, ciao', 23, 3);
INSERT INTO EPISODE VALUES (28, 6, 'Todo pareció insignificante', 'Plus rien avait d importance', 24, 3);
INSERT INTO EPISODE VALUES (29, 7, 'Pequeñas vacaciones', 'Petites Vacances', 24, 3);
INSERT INTO EPISODE VALUES (30, 8, 'La deriva', 'La Dérive', 22, 3);
INSERT INTO EPISODE VALUES (31, 1, 'Game Over', 'Game Over', 23, 4);
INSERT INTO EPISODE VALUES (32, 2, 'La boda de Berlin', 'Le Mariage de Berlin', 25, 4);
INSERT INTO EPISODE VALUES (33, 3, 'Lección de anatomia', 'La Leçon d anatomie', 24, 4);
INSERT INTO EPISODE VALUES (34, 4, 'Suspiros de España', 'Paso-doble', 22, 4);
INSERT INTO EPISODE VALUES (35, 5, '5 minutos antes', 'Cinq minutes plus tôt', 24, 4);
INSERT INTO EPISODE VALUES (36, 6, 'KO tecnico', 'KO technique', 25, 4);
INSERT INTO EPISODE VALUES (37, 7, 'Tumbar la carpa', 'Frapper le QG', 23, 4);
INSERT INTO EPISODE VALUES (38, 8, 'Plan Paris', 'Le Plan Paris', 22, 4);
INSERT INTO EPISODE VALUES (39, 1, 'El final del camino', 'Au bout du rouleau', NULL, 5);
INSERT INTO EPISODE VALUES (40, 2, '¿Crees en la reencarnación?', 'Tu crois en la réincarnation ?', NULL, 5);
INSERT INTO EPISODE VALUES (41, 3, 'El espectáculo de la vida', 'Bienvenue au spectacle de la vie', NULL, 5);
INSERT INTO EPISODE VALUES (42, 4, 'Tu sitio en el cielo', 'Ta place au paradis', NULL, 5);
INSERT INTO EPISODE VALUES (43, 5, 'Vivir muchas vidas', 'Vis tes vies', NULL, 5);
INSERT INTO EPISODE VALUES (44, 6, 'Válvulas de escape', 'Trop de pression', NULL, 5);
INSERT INTO EPISODE VALUES (45, 7, 'Ciencia ilusionada', 'Science optimiste', NULL, 5);
INSERT INTO EPISODE VALUES (46, 8, 'La teoría de la elegancia', 'La Théorie de l élégance', NULL, 5);
INSERT INTO EPISODE VALUES (47, 9, 'Lo que se habla en la cama', 'Confidences sur l oreiller', NULL, 5);
INSERT INTO EPISODE VALUES (48, 10, 'Una tradición familiar', 'Une tradition familiale', NULL, 5);

--Insertion des données dans la table PAYS--
INSERT INTO PAYS (idPays, NomPays) VALUES (1, 'Espagne');
INSERT INTO PAYS (idPays, NomPays) VALUES (2, 'Panama');
INSERT INTO PAYS (idPays, NomPays) VALUES (3, 'Italie');
INSERT INTO PAYS (idPays, NomPays) VALUES (4, 'Indonésie');
INSERT INTO PAYS (idPays, NomPays) VALUES (5, 'Argentine');
INSERT INTO PAYS (idPays, NomPays) VALUES (6, 'Philippines');
INSERT INTO PAYS (idPays, NomPays) VALUES (7, 'Thailande');

--Insertion des données dans la table VILLE--
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (1, 'Guna Yala', 2);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (2, 'Madrid', 1);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (3, 'Florence', 3);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (4, 'Java', 4);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (5, 'La Pampa', 5);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (6, 'Tolède', 1);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (7, 'Palawan', 6);
INSERT INTO VILLE (idVille, NomVille, VillePays) VALUES (8, 'Pattaya', 7);

-- Insertions des données dans la table PERSONNAGE--
INSERT INTO PERSONNAGE VALUES (1, 'Marquina', 'Sergio', 'le Professeur', 1, 47, null, 1);
INSERT INTO PERSONNAGE VALUES (2, 'Olliveira', 'Silene', 'Tokyo', 1, 48, 47, 2);
INSERT INTO PERSONNAGE VALUES (3, 'Murillo', 'Raquel', 'Lisbonne', 1, 48, NULL, 3);
INSERT INTO PERSONNAGE VALUES (4, 'De Fonollosa', 'Andrés', 'Berlin', 1, 47, 20, 4);
INSERT INTO PERSONNAGE VALUES (5, 'Jimenez', 'Agata', 'Nairobi', 1, 38, 38, 5);
INSERT INTO PERSONNAGE VALUES (6, 'Cortés', 'Anibal', 'Rio', 1, 48, NULL, 6);
INSERT INTO PERSONNAGE VALUES (7, 'Ramos', 'Daniel', 'Denver', 1, 48, NULL, 7);
INSERT INTO PERSONNAGE VALUES (8, 'Ramos', 'Agustin', 'Moscou', 1, 22, 19, 8);
INSERT INTO PERSONNAGE VALUES (9, 'Dragic', 'Mirko', 'Helsinki', 1, 48, NULL, 9);
INSERT INTO PERSONNAGE VALUES (10, 'Gaztambide', 'Monica', 'Stockholm', 1, 48, NULL, 10);
INSERT INTO PERSONNAGE VALUES (11, 'Mostovoi', 'Dimitri', 'Oslo', 1, 6, 13, 11);
INSERT INTO PERSONNAGE VALUES (12, 'Roman', 'Arturo', 'Arturito', 1, 20, NULL, 12);
INSERT INTO PERSONNAGE VALUES (13, 'Berote', 'Martin', 'Palerme', 23, 48, NULL, 16);
INSERT INTO PERSONNAGE VALUES (14, 'Lopez', 'Santiago', 'Bogota', 23, 48, NULL, 17);
INSERT INTO PERSONNAGE VALUES (15, 'René', 'Yakov', 'Marseille', 23, 48, NULL, 18);
INSERT INTO PERSONNAGE VALUES (16, NULL, 'Julia', 'Manille', 23, 48, NULL, 19);
INSERT INTO PERSONNAGE VALUES (17, 'Rubio', 'Angel', NULL, 23, 48, NULL, 13);
INSERT INTO PERSONNAGE VALUES (18, 'Parker', 'Alison', NULL, 31, 48, NULL, 14);
INSERT INTO PERSONNAGE VALUES (19, 'Murillo', 'Marivi', NULL, 1, 30, NULL, 15);
INSERT INTO PERSONNAGE VALUES (20, 'Tamayo', 'Luis', NULL, 15, 48, NULL, 20);
INSERT INTO PERSONNAGE VALUES (21, 'Sierra', 'Alicia', NULL, 15, 48, NULL, 21);

--Insertion des données dans la table LIEU--
INSERT INTO LIEU VALUES (1, 'Archipel de Guna Yala', 1);
INSERT INTO LIEU VALUES (2, 'Banque d Espagne', 2);
INSERT INTO LIEU VALUES (3, 'Café "Le Hanoï"', 2);
INSERT INTO LIEU VALUES (4, 'Casse de voitures', 2);
INSERT INTO LIEU VALUES (5, 'Fabrique de la Monnaie', 2);
INSERT INTO LIEU VALUES (6, 'Florence', 3);
INSERT INTO LIEU VALUES (7, 'Java', 4);
INSERT INTO LIEU VALUES (8, 'La Pampa', 5);
INSERT INTO LIEU VALUES (9, 'Madrid', 2);
INSERT INTO LIEU VALUES (10, 'Maison de Raquel', 2);
INSERT INTO LIEU VALUES (11, 'Maison de Tolede', 6);
INSERT INTO LIEU VALUES (12, 'Monastere', 3);
INSERT INTO LIEU VALUES (13, 'Palawan', 7);
INSERT INTO LIEU VALUES (14, 'Tente de la police 1', 2);
INSERT INTO LIEU VALUES (15, 'Tente de la police 2', 2);
INSERT INTO LIEU VALUES (16, 'Entrepot', 2);
INSERT INTO LIEU VALUES (17, 'Camping-car du professeur', 2);
INSERT INTO LIEU VALUES (18, 'Déservoir d orage', 2);

--Insertion des données dans la table EVENEMENT--
INSERT INTO EVENEMENT VALUES (1, 'Capture de Rio.', 23, 1);
INSERT INTO EVENEMENT VALUES (2, 'Mort de Nairobi.', 38, 2);
INSERT INTO EVENEMENT VALUES (3, 'Mort de Tokyo.', 41, 2);
INSERT INTO EVENEMENT VALUES (4, 'Début du bracage.', 24, 2);
INSERT INTO EVENEMENT VALUES (5, 'Fin du bracage.', 48, 2);
INSERT INTO EVENEMENT VALUES (6, 'Rencontre Professeur et Raquel.', 2, 3);
INSERT INTO EVENEMENT VALUES (7, 'Raquel menace le professeur avec son arme et exige des explications.', 11, 3);
INSERT INTO EVENEMENT VALUES (8, 'Raquel decourvre la reel identité du professeur.', 18, 3);
INSERT INTO EVENEMENT VALUES (9, 'Le professeur se deguise en SDF pour echapper a la police.', 7, 4);
INSERT INTO EVENEMENT VALUES (10, 'Le professeur detruit les preuves dans la voiture.', 7, 4);
INSERT INTO EVENEMENT VALUES (11, 'Debut du bracage.', 1, 5);
INSERT INTO EVENEMENT VALUES (12, 'Mort de Berlin', 22, 5);
INSERT INTO EVENEMENT VALUES (13, 'Mort de Moscou', 19, 5);
INSERT INTO EVENEMENT VALUES (14, 'Mort d Oslo', 14, 5);
INSERT INTO EVENEMENT VALUES (15, 'Fin bracage.', 22, 5);
INSERT INTO EVENEMENT VALUES (16, 'Flashback. Sergio, le Professeur, qui rejoint son frère Andres, Berlin, à Florence en Italie.', 23, 6);
INSERT INTO EVENEMENT VALUES (17, 'Andres révèle à son frère qu il est atteint par la même maladie que sa mère.', 23, 6);
INSERT INTO EVENEMENT VALUES (18, 'Denver et Monica parte vivre a Java après la fin du bracage.', 22, 7);
INSERT INTO EVENEMENT VALUES (19, 'Denver et Monica rejoignent le professeur.', 23, 7);
INSERT INTO EVENEMENT VALUES (20, 'Helsinki et Nairobi se rejoigne dans la Pampa en Argentine.', 23, 8);
INSERT INTO EVENEMENT VALUES (21, 'le Professeur fait déverser par des dirigeables une pluie de billets.', 23, 9);
INSERT INTO EVENEMENT VALUES (22, 'le Professeur a failli empoisonner Marivi, la mère de Raquel.', 13, 10);
INSERT INTO EVENEMENT VALUES (23, 'Préparation du braquage de la fabrique de la monaie et du timbre.', 1, 11);
INSERT INTO EVENEMENT VALUES (24, 'Découverte de la maison de Tolede par la police.', 13, 11);
INSERT INTO EVENEMENT VALUES (25, 'Préparation du casse de la banque d espagne.', 23, 12);
INSERT INTO EVENEMENT VALUES (26, 'Raquel retrouve le professeur.', 22, 13);
INSERT INTO EVENEMENT VALUES (27, 'Tokyo cherche le professeur.', 23, 13);
INSERT INTO EVENEMENT VALUES (28, 'Raquel mène la négociation avec le Professeur.', 1, 14);
INSERT INTO EVENEMENT VALUES (29, 'Le Colonel Tamayo et l inspectrice Alicia Sierra mènnent les opérations pour faire arreter le braquage.', 23, 15);
INSERT INTO EVENEMENT VALUES (30, 'La plaque du professeur pour les deux première partie.', 1, 16);
INSERT INTO EVENEMENT VALUES (31, 'La premiere nuit enssemble enre le Professeur et Raquel.', 12, 16);
INSERT INTO EVENEMENT VALUES (32, 'Le quartier général devient celui du Professeur et de Raquel', 23, 17);
INSERT INTO EVENEMENT VALUES (33, 'Le  Professeur change de repère après que Lisbone se soit faite capturé.', 31, 18);

--Insertion des données dans la table cause_par--
INSERT INTO cause_par VALUES (6, 1);
INSERT INTO cause_par VALUES (5, 2);
INSERT INTO cause_par VALUES (21, 2);
INSERT INTO cause_par VALUES (2, 3);
INSERT INTO cause_par VALUES (1, 4);
INSERT INTO cause_par VALUES (2, 4);
INSERT INTO cause_par VALUES (3, 4);
INSERT INTO cause_par VALUES (5, 4);
INSERT INTO cause_par VALUES (6, 4);
INSERT INTO cause_par VALUES (7, 4);
INSERT INTO cause_par VALUES (9, 4);
INSERT INTO cause_par VALUES (10, 4);
INSERT INTO cause_par VALUES (12, 4);
INSERT INTO cause_par VALUES (13, 4);
INSERT INTO cause_par VALUES (14, 4);
INSERT INTO cause_par VALUES (15, 4);
INSERT INTO cause_par VALUES (16, 4);
INSERT INTO cause_par VALUES (1, 5);
INSERT INTO cause_par VALUES (2, 5);
INSERT INTO cause_par VALUES (3, 5);
INSERT INTO cause_par VALUES (6, 5);
INSERT INTO cause_par VALUES (7, 5);
INSERT INTO cause_par VALUES (9, 5);
INSERT INTO cause_par VALUES (10, 5);
INSERT INTO cause_par VALUES (12, 5);
INSERT INTO cause_par VALUES (13, 5);
INSERT INTO cause_par VALUES (14, 5);
INSERT INTO cause_par VALUES (15, 5);
INSERT INTO cause_par VALUES (16, 5);
INSERT INTO cause_par VALUES (1, 6);
INSERT INTO cause_par VALUES (3, 6);
INSERT INTO cause_par VALUES (1, 7);
INSERT INTO cause_par VALUES (3, 7);
INSERT INTO cause_par VALUES (3, 8);
INSERT INTO cause_par VALUES (1, 9);
INSERT INTO cause_par VALUES (1, 10);
INSERT INTO cause_par VALUES (1, 11);
INSERT INTO cause_par VALUES (2, 11);
INSERT INTO cause_par VALUES (3, 11);
INSERT INTO cause_par VALUES (4, 11);
INSERT INTO cause_par VALUES (5, 11);
INSERT INTO cause_par VALUES (6, 11);
INSERT INTO cause_par VALUES (7, 11);
INSERT INTO cause_par VALUES (8, 11);
INSERT INTO cause_par VALUES (9, 11);
INSERT INTO cause_par VALUES (10, 11);
INSERT INTO cause_par VALUES (11, 11);
INSERT INTO cause_par VALUES (12, 11);
INSERT INTO cause_par VALUES (18, 11);
INSERT INTO cause_par VALUES (17, 11);
INSERT INTO cause_par VALUES (4, 12);
INSERT INTO cause_par VALUES (8, 13);
INSERT INTO cause_par VALUES (11, 14);
INSERT INTO cause_par VALUES (1, 15);
INSERT INTO cause_par VALUES (2, 15);
INSERT INTO cause_par VALUES (3, 15);
INSERT INTO cause_par VALUES (5, 15);
INSERT INTO cause_par VALUES (6, 15);
INSERT INTO cause_par VALUES (7, 15);
INSERT INTO cause_par VALUES (9, 15);
INSERT INTO cause_par VALUES (10, 15);
INSERT INTO cause_par VALUES (12, 15);
INSERT INTO cause_par VALUES (18, 15);
INSERT INTO cause_par VALUES (17, 15);
INSERT INTO cause_par VALUES (1, 16);
INSERT INTO cause_par VALUES (4, 16);
INSERT INTO cause_par VALUES (1, 17);
INSERT INTO cause_par VALUES (4, 17);
INSERT INTO cause_par VALUES (7, 18);
INSERT INTO cause_par VALUES (10, 18);
INSERT INTO cause_par VALUES (7, 19);
INSERT INTO cause_par VALUES (10, 19);
INSERT INTO cause_par VALUES (5, 20);
INSERT INTO cause_par VALUES (9, 20);
INSERT INTO cause_par VALUES (1, 21);
INSERT INTO cause_par VALUES (1, 22);
INSERT INTO cause_par VALUES (19, 22);
INSERT INTO cause_par VALUES (1, 23);
INSERT INTO cause_par VALUES (2, 23);
INSERT INTO cause_par VALUES (4, 23);
INSERT INTO cause_par VALUES (5, 23);
INSERT INTO cause_par VALUES (6, 23);
INSERT INTO cause_par VALUES (7, 23);
INSERT INTO cause_par VALUES (8, 23);
INSERT INTO cause_par VALUES (9, 23);
INSERT INTO cause_par VALUES (10, 23);
INSERT INTO cause_par VALUES (11, 23);
INSERT INTO cause_par VALUES (1, 24);
INSERT INTO cause_par VALUES (3, 24);
INSERT INTO cause_par VALUES (17, 24);
INSERT INTO cause_par VALUES (1, 25);
INSERT INTO cause_par VALUES (2, 25);
INSERT INTO cause_par VALUES (3, 25);
INSERT INTO cause_par VALUES (5, 25);
INSERT INTO cause_par VALUES (6, 25);
INSERT INTO cause_par VALUES (7, 25);
INSERT INTO cause_par VALUES (9, 25);
INSERT INTO cause_par VALUES (10, 25);
INSERT INTO cause_par VALUES (13, 25);
INSERT INTO cause_par VALUES (14, 25);
INSERT INTO cause_par VALUES (15, 25);
INSERT INTO cause_par VALUES (16, 25);
INSERT INTO cause_par VALUES (1, 26);
INSERT INTO cause_par VALUES (3, 26);
INSERT INTO cause_par VALUES (1, 27);
INSERT INTO cause_par VALUES (2, 27);
INSERT INTO cause_par VALUES (1, 28);
INSERT INTO cause_par VALUES (3, 28);
INSERT INTO cause_par VALUES (20, 29);
INSERT INTO cause_par VALUES (21, 29);
INSERT INTO cause_par VALUES (1, 30);
INSERT INTO cause_par VALUES (1, 31);
INSERT INTO cause_par VALUES (3, 31);
INSERT INTO cause_par VALUES (1, 32);
INSERT INTO cause_par VALUES (3, 32);
INSERT INTO cause_par VALUES (1, 33);

--Insertion des données dans la table est_en_lien--
INSERT INTO est_en_lien VALUES (1, 1, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (2, 1, 3, 'Couple');
INSERT INTO est_en_lien VALUES (3, 1, 4, 'Frère');
INSERT INTO est_en_lien VALUES (4, 1, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (5, 1, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (6, 1, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (7, 1, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (8, 1, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (9, 1, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (10, 1, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (11, 1, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (12, 1, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (13, 1, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (14, 1, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (15, 1, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (16, 2, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (17, 2, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (18, 2, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (19, 2, 5, 'Amie');
INSERT INTO est_en_lien VALUES (20, 2, 6, 'Couple');
INSERT INTO est_en_lien VALUES (21, 2, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (22, 2, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (23, 2, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (24, 2, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (25, 2, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (26, 2, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (27, 2, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (28, 2, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (29, 2, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (30, 2, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (31, 3, 1, 'Couple');
INSERT INTO est_en_lien VALUES (32, 3, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (33, 3, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (34, 3, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (35, 3, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (36, 3, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (37, 3, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (38, 3, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (39, 3, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (40, 3, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (41, 3, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (42, 3, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (43, 3, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (44, 3, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (45, 3, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (46, 4, 1, 'Frère');
INSERT INTO est_en_lien VALUES (47, 4, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (48, 4, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (49, 4, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (50, 4, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (51, 4, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (52, 4, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (53, 4, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (54, 4, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (55, 4, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (56, 4, 13, 'Ancien Amant');
INSERT INTO est_en_lien VALUES (57, 5, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (58, 5, 2, 'Amie');
INSERT INTO est_en_lien VALUES (59, 5, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (60, 5, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (61, 5, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (62, 5, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (63, 5, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (64, 5, 9, 'Ambigu');
INSERT INTO est_en_lien VALUES (65, 5, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (66, 5, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (67, 5, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (68, 5, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (69, 5, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (70, 5, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (71, 5, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (72, 6, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (73, 6, 2, 'Couple');
INSERT INTO est_en_lien VALUES (74, 6, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (75, 6, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (76, 6, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (77, 6, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (78, 6, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (79, 6, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (80, 6, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (81, 6, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (82, 6, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (83, 6, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (84, 6, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (85, 6, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (86, 6, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (87, 7, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (88, 7, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (89, 7, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (90, 7, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (91, 7, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (92, 7, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (93, 7, 8, 'Fils/Père');
INSERT INTO est_en_lien VALUES (94, 7, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (95, 7, 10, 'Couple');
INSERT INTO est_en_lien VALUES (96, 7, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (97, 7, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (98, 7, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (99, 7, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (100, 7, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (101, 7, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (102, 8, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (103, 8, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (104, 8, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (105, 8, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (106, 8, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (107, 8, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (108, 8, 7, 'Père/Fils');
INSERT INTO est_en_lien VALUES (109, 8, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (110, 8, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (111, 8, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (112, 9, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (113, 9, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (114, 9, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (115, 9, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (116, 9, 5, 'Ambigu');
INSERT INTO est_en_lien VALUES (117, 9, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (118, 9, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (119, 9, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (120, 9, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (121, 9, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (122, 9, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (123, 9, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (124, 9, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (125, 9, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (126, 9, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (127, 10, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (128, 10, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (129, 10, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (130, 10, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (131, 10, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (132, 10, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (133, 10, 7, 'Couple');
INSERT INTO est_en_lien VALUES (134, 10, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (135, 10, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (136, 10, 11, 'Coéquipier');
INSERT INTO est_en_lien VALUES (137, 10, 12, 'Ex');
INSERT INTO est_en_lien VALUES (138, 10, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (139, 10, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (140, 10, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (141, 10, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (142, 10, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (143, 11, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (144, 11, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (145, 11, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (146, 11, 4, 'Coéquipier');
INSERT INTO est_en_lien VALUES (147, 11, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (148, 11, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (149, 11, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (150, 11, 8, 'Coéquipier');
INSERT INTO est_en_lien VALUES (151, 11, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (152, 11, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (153, 12, 10, 'Ex');
INSERT INTO est_en_lien VALUES (154, 13, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (155, 13, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (156, 13, 4, 'Ancien Amant');
INSERT INTO est_en_lien VALUES (157, 13, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (158, 13, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (159, 13, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (160, 13, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (161, 13, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (162, 13, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (163, 13, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (164, 13, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (165, 13, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (166, 13, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (167, 14, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (168, 14, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (169, 14, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (170, 14, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (171, 14, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (172, 14, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (173, 14, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (174, 14, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (175, 14, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (176, 14, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (177, 14, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (178, 14, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (179, 15, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (180, 15, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (181, 15, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (182, 15, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (183, 15, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (184, 15, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (185, 15, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (186, 15, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (187, 15, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (188, 15, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (189, 15, 16, 'Coéquipier');
INSERT INTO est_en_lien VALUES (190, 15, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (191, 16, 1, 'Coéquipier');
INSERT INTO est_en_lien VALUES (192, 16, 2, 'Coéquipier');
INSERT INTO est_en_lien VALUES (193, 16, 3, 'Coéquipier');
INSERT INTO est_en_lien VALUES (194, 16, 5, 'Coéquipier');
INSERT INTO est_en_lien VALUES (195, 16, 6, 'Coéquipier');
INSERT INTO est_en_lien VALUES (196, 16, 7, 'Coéquipier');
INSERT INTO est_en_lien VALUES (197, 16, 9, 'Coéquipier');
INSERT INTO est_en_lien VALUES (198, 16, 10, 'Coéquipier');
INSERT INTO est_en_lien VALUES (199, 16, 13, 'Coéquipier');
INSERT INTO est_en_lien VALUES (200, 16, 14, 'Coéquipier');
INSERT INTO est_en_lien VALUES (201, 16, 15, 'Coéquipier');
INSERT INTO est_en_lien VALUES (202, 16, 21, 'Ennemis');
INSERT INTO est_en_lien VALUES (203, 17, 3, 'Ami');
INSERT INTO est_en_lien VALUES (204, 3, 17, 'Ami');
INSERT INTO est_en_lien VALUES (205, 19, 3, 'Mère/Fille');
INSERT INTO est_en_lien VALUES (206, 3, 19, 'Fille/Mère');
INSERT INTO est_en_lien VALUES (207, 17, 20, 'Collègue');
INSERT INTO est_en_lien VALUES (208, 17, 21, 'Collègue');
INSERT INTO est_en_lien VALUES (209, 20, 17, 'Collègue');
INSERT INTO est_en_lien VALUES (210, 20, 21, 'Collègue');
INSERT INTO est_en_lien VALUES (211, 21, 17, 'Collègue');
INSERT INTO est_en_lien VALUES (212, 21, 20, 'Collègue');
INSERT INTO est_en_lien VALUES (213, 21, 1, 'Ennemis');
INSERT INTO est_en_lien VALUES (214, 21, 2, 'Ennemis');
INSERT INTO est_en_lien VALUES (215, 21, 3, 'Ennemis');
INSERT INTO est_en_lien VALUES (216, 21, 5, 'Ennemis');
INSERT INTO est_en_lien VALUES (217, 21, 6, 'Ennemis');
INSERT INTO est_en_lien VALUES (218, 21, 7, 'Ennemis');
INSERT INTO est_en_lien VALUES (219, 21, 9, 'Ennemis');
INSERT INTO est_en_lien VALUES (220, 21, 10, 'Ennemis');
INSERT INTO est_en_lien VALUES (221, 21, 13, 'Ennemis');
INSERT INTO est_en_lien VALUES (222, 21, 14, 'Ennemis');
INSERT INTO est_en_lien VALUES (223, 21, 15, 'Ennemis');
INSERT INTO est_en_lien VALUES (224, 21, 16, 'Ennemis');
INSERT INTO est_en_lien VALUES (225, 18, 1, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (226, 18, 2, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (227, 18, 3, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (228, 18, 5, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (229, 18, 6, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (230, 18, 7, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (231, 18, 9, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (232, 18, 10, 'Otage/Braqueur');
INSERT INTO est_en_lien VALUES (233, 1, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (234, 2, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (235, 3, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (236, 5, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (237, 6, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (238, 7, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (239, 9, 18, 'Braqueur/Otage');
INSERT INTO est_en_lien VALUES (240, 10, 18, 'Braqueur/Otage');
